import re
a = '[04&#58;15&#46;86]但偏偏雨渐渐把距离吹得好远&#10;[04&#58;19&#46;29]好不容易又能再多爱一天&#10;[04&#58;22&#46;79]但故事的最后你好像还是说了拜'
s = re.sub('&#10;','\n',a)
print(s)
b = re.sub('.*?]','',s)   
c = re.sub('.*]','',s)
d = re.findall('[^x00-xff]+',s)
e = re.sub('\\[.*]','',s)
f = re.sub('\[.*]','',s)
g = re.sub('[\d\[\]\&\#\;]','',s)
h = re.findall('.*?](.*)',s)
i = re.findall('.*?(\d.*?\d)',s)
j = re.findall('.*?(\d.*\d)',s)
k = re.findall('.*(\d.*?\d)',s)
l = re.findall('.*(\d.*\d)',s)

m = re.findall('.*?(\d.*?\d)',a)
n = re.findall('.*?(\d.*\d)',a)
o = re.findall('.*(\d.*?\d)',a)
p = re.findall('.*(\d.*\d)',a)
print(b)
# print(type(t))
# print(type(m))
# print(c)
# print(d)
# print(e)
# print(f)
# print(g)
# print(h)
# print(i)
# print(j)
# print(k)
# print(l)
# print(m)
# print(n)
# print(o)
# print(p)

